---
title: "EH22_CCA"
output: html_document
date: "2025-04-21"
---

```{r setup, include=FALSE}
library(vegan)
library(ggplot2)
df_genecounts<-read.csv("/Users/houlin/Desktop/Research/Ecohab/Ecohab22/metatranscriptoms/genecounts/Ecohab22_rawgenecounts.csv", row.names = 1)  
df_tpm<-read.csv("/Users/houlin/Desktop/Research/Ecohab/Ecohab22/metatranscriptoms/Ecohab22_TPM_annotated-taxfull.csv", row.names = 1)
df_data<-df_tpm[,4:66]
hellinger_data <- decostand(df_data, method = "hellinger")
annotations<-df_tpm[,97:119]

metadata<-read.csv("/Users/houlin/Desktop/Research/Ecohab/Ecohab22/data/Ecohab22_metadata_042125.csv",row.names=1)  
env_data <- metadata[rownames(metadata) %in% colnames(df_genecounts), ]
```

## Including Plots



```{r,fig.width=9, fig.height=8}
dataset_use<-t(hellinger_data)
#### set the dataset #####
env_vars <- env_data[, c("Mean_Temp", "Mean_Salinity", "Mean_Chl")]
cca_model <- cca(dataset_use ~ Mean_Temp + Mean_Salinity + Mean_Chl, data = env_vars)
plot(cca_model,xlim=c(-4, 2), ylim=c(-3, 5),
     display = c("sites","species", "bp"), main = "EH22 Metatranscriptomics")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
