---
title: "EH22_diatom_deseq2"
output: html_document
date: "2026-04-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(DESeq2)
library(tidyverse)
library(Matrix)
library(igraph)
library(magrittr) 
library(dplyr)
library(otuSummary)
library(reshape2) # has the melt function, which I use to wrangle data
library("BiocParallel")
pass <- function(x){x}
```

```{r}
df_gene<-read.delim('/Users/houlin/Desktop/Research/Ecohab/Ecohab22/metatranscriptoms/genecounts/Diatom_Ecohab22_genecounts_KO_grouped.tsv',sep='\t',row.names = 1)
metadata<- read.csv("/Users/houlin/Desktop/Research/Ecohab/Ecohab22/metatranscriptoms/genecounts/metadata_cluster.csv",row.names = 1)
metadata<-metadata[colnames(df_gene),]
metadata$Phase_group <- factor(metadata$Phase_group)
metadata$Phase_group<- relevel(metadata$Phase_group, ref = "Bloom-1")
```


```{r}
metadata$Cluster <- factor(
  metadata$Cluster,
  levels = c(1,2,3,4,5),# 1,2,3,4,5
  labels = c("B1","B1R","B2","NB","PB")
)
metadata$Cluster <- relevel(metadata$Cluster, ref = "B1")
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = df_gene,
                                colData = metadata,
                                design = ~ Cluster)
# filter by keeping genes with sum above 10 counts
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep, ]
dds<- estimateSizeFactors(dds,type = "poscount")

register(MulticoreParam(12))
start_time <- Sys.time()
dds <- DESeq(dds)
print(Sys.time() - start_time)
```

```{r}
res_pre_shr <- lfcShrink(dds, coef = "Cluster_nonupwelling_vs_upwelling", type = "apeglm")

output_dir <- "/Users/houlin/Desktop/DelMar_ESP/DESeq2_data/eukaryotes/"
write.csv(res_pre_shr, file = paste0(output_dir,tax,"_DESeq2_nonupwelling_vs_upwelling_normal_",
                                     dataset_name,"_Class_Pfam_cluster2.csv"))
# write.csv(res_post_shr, file = paste0(output_dir,tax,"_DESeq2_postbloom_vs_bloom_normal_",dataset_name,"_",level,"_Pfam_Chattonella_bloom.csv"))
print('finish DEseq')
print(tax)
```

